<a href="https://colab.research.google.com/github/Sreeja1585/23CSBTB27-28/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr=np.array([[1,2],[3,6]])
print(arr)
arr1=arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
arr2=arr=np.array([[1,2,9],[4,2,6],[7,8,9]])
print(arr1)
print(arr2)
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1,arr2))

[[1 2]
 [3 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 9]
 [4 2 6]
 [7 8 9]]
[[ 2  4 12]
 [ 8  7 12]
 [14 16 18]]
[[ 0  0 -6]
 [ 0  3  0]
 [ 0  0  0]]
[[ 1  4 27]
 [16 10 36]
 [49 64 81]]
[[1.         1.         0.33333333]
 [1.         2.5        1.        ]
 [1.         1.         1.        ]]
